game = [
    {"name": "Alice", "country": "USA", "followers": 1200000, "occupation": "Content Creator"},
    {"name": "Ravi", "country": "India", "followers": 900000, "occupation": "Influencer"},
    {"name": "Maria", "country": "Brazil", "followers": 750000, "occupation": "Travel Blogger"},
    {"name": "John", "country": "UK", "followers": 500000, "occupation": "Photographer"},
    {"name": "Lena", "country": "Germany", "followers": 400000, "occupation": "Artist"},
    {"name": "Suki", "country": "Japan", "followers": 300000, "occupation": "Musician"},
    {"name": "Emma", "country": "Canada", "followers": 200000, "occupation": "Chef"},
    {"name": "Jack", "country": "Australia", "followers": 150000, "occupation": "Fitness Trainer"},
    {"name": "Chloe", "country": "France", "followers": 100000, "occupation": "Fashion Designer"},
    {"name": "Marco", "country": "Italy", "followers": 80000, "occupation": "Writer"},
    {"name": "Zara", "country": "Spain", "followers": 70000, "occupation": "Blogger"},
    {"name": "Amina", "country": "Egypt", "followers": 60000, "occupation": "Social Media Manager"},
    {"name": "Nina", "country": "Netherlands", "followers": 50000, "occupation": "Graphic Designer"},
    {"name": "Liam", "country": "Ireland", "followers": 40000, "occupation": "Tech Reviewer"},
    {"name": "Mia", "country": "New Zealand", "followers": 35000, "occupation": "Vlogger"},
    {"name": "Omar", "country": "Saudi Arabia", "followers": 30000, "occupation": "Entrepreneur"},
    {"name": "Anya", "country": "Russia", "followers": 25000, "occupation": "Artist"},
    {"name": "Sofia", "country": "Portugal", "followers": 20000, "occupation": "Photographer"},
    {"name": "Yuki", "country": "South Korea", "followers": 15000, "occupation": "Fashion Influencer"},
    {"name": "Dante", "country": "Mexico", "followers": 10000, "occupation": "Musician"},
    {"name": "Santiago", "country": "Chile", "followers": 9000, "occupation": "Chef"},
    {"name": "Kira", "country": "Finland", "followers": 8500, "occupation": "Writer"},
    {"name": "Ethan", "country": "USA", "followers": 8000, "occupation": "Podcaster"},
    {"name": "Alyssa", "country": "Philippines", "followers": 7500, "occupation": "Blogger"},
    {"name": "Mateo", "country": "Argentina", "followers": 7000, "occupation": "Fitness Coach"},
    {"name": "Lila", "country": "Turkey", "followers": 6500, "occupation": "Artist"},
    {"name": "Rafael", "country": "Colombia", "followers": 6000, "occupation": "Musician"},
    {"name": "Chad", "country": "South Africa", "followers": 5500, "occupation": "Travel Writer"},
    {"name": "Jasmine", "country": "Singapore", "followers": 5000, "occupation": "Influencer"},
    {"name": "Leo", "country": "Vietnam", "followers": 4500, "occupation": "Photographer"},
    {"name": "Hana", "country": "Malaysia", "followers": 4000, "occupation": "Chef"},
    {"name": "Khalid", "country": "UAE", "followers": 3500, "occupation": "Tech Entrepreneur"},
    {"name": "Nora", "country": "Sweden", "followers": 3000, "occupation": "Artist"},
    {"name": "Amir", "country": "Jordan", "followers": 2500, "occupation": "Digital Marketer"},
    {"name": "Sasha", "country": "Ukraine", "followers": 2000, "occupation": "Blogger"},
    {"name": "Daria", "country": "Poland", "followers": 1500, "occupation": "Photographer"},
    {"name": "Isla", "country": "Scotland", "followers": 1000, "occupation": "Designer"},
    {"name": "Raj", "country": "Nepal", "followers": 750, "occupation": "Travel Guide"},
    {"name": "Zoe", "country": "Belgium", "followers": 500, "occupation": "Content Creator"},
    {"name": "Samir", "country": "Bangladesh", "followers": 250, "occupation": "Social Media Consultant"},
    {"name": "Olivia", "country": "USA", "followers": 1800000, "occupation": "Travel Blogger"},
    {"name": "Lucas", "country": "Canada", "followers": 1600000, "occupation": "Software Developer"},
    {"name": "Maya", "country": "Australia", "followers": 1400000, "occupation": "Content Creator"},
    {"name": "Noah", "country": "Germany", "followers": 1300000, "occupation": "Designer"},
    {"name": "Sophia", "country": "UK", "followers": 1200000, "occupation": "Photographer"},
    {"name": "Aiden", "country": "India", "followers": 1100000, "occupation": "Vlogger"},
    {"name": "Ella", "country": "Brazil", "followers": 1000000, "occupation": "Chef"},
    {"name": "Liam", "country": "Japan", "followers": 900000, "occupation": "Musician"},
    {"name": "Chloe", "country": "France", "followers": 800000, "occupation": "Artist"},
    {"name": "James", "country": "Italy", "followers": 700000, "occupation": "Entrepreneur"},
    {"name": "Evelyn", "country": "Spain", "followers": 600000, "occupation": "Influencer"},
    {"name": "Benjamin", "country": "Netherlands", "followers": 550000, "occupation": "Travel Guide"},
    {"name": "Scarlett", "country": "South Korea", "followers": 500000, "occupation": "Fashion Designer"},
    {"name": "Henry", "country": "Russia", "followers": 450000, "occupation": "Digital Marketer"},
    {"name": "Aria", "country": "Sweden", "followers": 400000, "occupation": "Social Media Consultant"},
    {"name": "Alexander", "country": "Turkey", "followers": 350000, "occupation": "Photographer"},
    {"name": "Grace", "country": "Norway", "followers": 300000, "occupation": "Graphic Designer"},
    {"name": "Elijah", "country": "Finland", "followers": 250000, "occupation": "Podcaster"},
    {"name": "Isabella", "country": "Greece", "followers": 200000, "occupation": "Content Writer"},
    {"name": "Jack", "country": "Argentina", "followers": 180000, "occupation": "Chef"},
    {"name": "Zoe", "country": "Egypt", "followers": 160000, "occupation": "Artist"},
    {"name": "Leo", "country": "South Africa", "followers": 140000, "occupation": "Photographer"},
    {"name": "Mila", "country": "Chile", "followers": 120000, "occupation": "Travel Blogger"},
    {"name": "Max", "country": "Peru", "followers": 110000, "occupation": "Influencer"},
    {"name": "Layla", "country": "Colombia", "followers": 100000, "occupation": "Vlogger"},
    {"name": "Luke", "country": "Philippines", "followers": 90000, "occupation": "Fitness Trainer"},
    {"name": "Nina", "country": "Vietnam", "followers": 80000, "occupation": "Chef"},
    {"name": "Ryan", "country": "Singapore", "followers": 70000, "occupation": "Designer"},
    {"name": "Lily", "country": "Malaysia", "followers": 60000, "occupation": "Artist"},
    {"name": "Owen", "country": "UAE", "followers": 50000, "occupation": "Musician"},
    {"name": "Ella", "country": "Morocco", "followers": 45000, "occupation": "Content Creator"},
]